source 'https://rubygems.org'
gem "bubble-wrap", "~> 1.3.0", :require => 'bubble-wrap/all'
gem 'rake'
gem 'cocoapods'
gem 'motion-cocoapods'
gem 'motion-testflight'
gem 'guard'
gem 'guard-rake'
gem 'terminal-notifier-guard'
gem 'rb-fsevent', '~> 0.9.1'